### ISSUE TITLE
Transport messages between workers ?

### ISSUE THREAD

**Issue by folospace** [dosgo/sw-socketio#3]
I know swoole can send data to any client,  but with this package, I cant send data to some clients while swoole config workers greater than one. How can I approach that ?

**Comment by dosgo** [comment]
Worker_num >1 ， but dispatch_mode can only be 4.

**Comment by dosgo** [comment]
I suggest you add a user authentication on the onconnection, save the socket handle and uid, and then you can directly pass uid->socket->send().

**Comment by folospace** [comment]
"dispatch_mode=4" works, seems like all clients connected to the same worker. 
Will this worker be overloaded on massive connections ?

**Comment by dosgo** [comment]
"dispatch_mode=4" is based on ip hash. If it is externally served, IP may not be concentrated.

ip2long(ClientIP) % worker_num
https://wiki.swoole.com/wiki/page/277.html

**Comment by dosgo** [comment]
Whether the same worker is determined according to ip2long(ClientIP)% worker_num, if ClientIP is scattered, it will not be the same worker.

**Comment by dosgo** [comment]
Which country are you from? My English is translated by Google, please forgive me.

**Comment by folospace** [comment]
I bet we come from the same country, just only I am used to English :)
